# Generated by Django 5.2.15 on 2026-07-07 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='資格名')),
                ('exam_date', models.DateField(verbose_name='試験日')),
                ('target_hours', models.PositiveIntegerField(default=0, verbose_name='目標勉強時間')),
                ('target_score', models.PositiveIntegerField(default=0, verbose_name='目標点数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '資格',
                'verbose_name_plural': '資格',
            },
        ),
    ]
