# Generated by Django 5.2.15 on 2026-09-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='現在学習中'),
        ),
    ]
