# Generated by Django 5.2.15 on 2026-07-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学習日')),
                ('study_time', models.PositiveIntegerField(verbose_name='学習時間（分）')),
                ('content', models.TextField(verbose_name='学習内容')),
                ('understanding', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='理解度')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='goals.qualification', verbose_name='資格')),
            ],
            options={
                'verbose_name': '学習記録',
                'verbose_name_plural': '学習記録',
                'ordering': ['-study_date'],
            },
        ),
    ]
